image: python:3.10-alpine

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"
    GIT_STRATEGY: clone


stages:
- setup_environment
- testing

setup:
    stage:
    needs: []
    tags: env:docker
    script:
        - pip install poetry
        - poetry install

test:
    stage: testing
    needs: []
    tags:
        - env:docker
    script:
        - poetry run python -m unittest discover -s tests/ -t tests/

