image: ubuntu:22.04

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
- testing


test:
    stage: testing
    needs: []
    tags:
        - env:docker
    script:
        - python -m unittest discover -s tests/ -t tests/

